### ISSUE TITLE
HRNet Checkpoint fiel

### ISSUE THREAD

**Issue by pyxploiter** [JubSteven/POEM-v2#2]
Hi,

Where can I get the checkpoint file for HRNet ([mentioned here](https://github.com/JubSteven/POEM-v2/blob/0b0f07ad025828c11aba3824732cf2c5eb226746/config/release/train_small.yaml#L183))

Thanks

**Comment by JubSteven** [comment]
Hi, you can use this [script](https://github.com/JubSteven/POEM-v2/blob/0b0f07ad025828c11aba3824732cf2c5eb226746/prepare/download_hrnet.sh#L1) to download the checkpoints for HRNet to the default path. 

Hope this helps

**Comment by emmm-50** [comment]
Hi, 

I tried using the provided download script `prepare/download_hrnet.sh` to fetch the HRNet checkpoints, but it fails with the following error:

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account.</Message>
</Error>

<img width="1673" height="286" alt="Image" src="https://github.com/user-attachments/assets/6c69a900-ac0a-480a-8f96-d3edcbc319b8" />

This happens both in the browser and via the script, so it seems the Azure Blob storage no longer allows public access. Could you please provide an alternative download link or a mirror for the HRNet checkpoints?

Thanks!

**Comment by EmbodiedAI-Group** [comment]
> Hi,
> 
> I tried using the provided download script `prepare/download_hrnet.sh` to fetch the HRNet checkpoints, but it fails with the following error:
> 
> `PublicAccessNotPermitted` Public access is not permitted on this storage account. <img alt="Image" width="1673" height="286" src="https://private-user-images.githubusercontent.com/177803462/566846054-6c69a900-ac0a-480a-8f96-d3edcbc319b8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODc5OTIyNTUsIm5iZiI6MTc4Nzk5MTk1NSwicGF0aCI6Ii8xNzc4MDM0NjIvNTY2ODQ2MDU0LTZjNjlhOTAwLWFjMGEtNDgwYS04Zjk2LWQzZWRjYmMzMTliOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDgyOVQwODI1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OThhYzEyZjYxYmEwMzQ3NzZhOGQ0NGMxNjc0NDQ1OTBiOWQ4ODkyODI2ZjdjOTU0NDY2MjA4OTEyNGZhYWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.aH5AYfy2XQVf2-AZEYQ1pHV5JneCJIvnT1QWNGRCT-8">
> This happens both in the browser and via the script, so it seems the Azure Blob storage no longer allows public access. Could you please provide an alternative download link or a mirror for the HRNet checkpoints?
> 
> Thanks!

Same problem, have you solved? How to solve this problem?
