### ISSUE TITLE
Looking for configuration files of your ablation study

### ISSUE THREAD

**Issue by pyxploiter** [JubSteven/POEM-v2#3]
Hello,

Can you please provide the configuration files for your ablation studies?  Particularly:

- Training POEMv1, MvP, PE-MeshTR, FTL-MeshTR on Sharded Datasets [[This repo](https://github.com/lixiny/POEM/) uses unsharded data]
- Training POEMv2 on each dataset separately: I can probably do this by updating provided released config such that "MIX_RATIO: 1" and "DATASET_LIST = ["DexYCB"], Right?

Thanks.

**Comment by JubSteven** [comment]
Hi,

- The ablation studies in question are conducted using POEM-v1 (i.e. the original version), so unfortunately we haven't adapted POEM-v2 for these configurations.
- Yes, that is correct. It's advised to train the model using similar hyper-parameter settings as POEM-v1
